name: Publish Daily Podcast

on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC ≈ 07:00 Europe/Madrid
  workflow_dispatch:       # Allows manual runs

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensures GITHUB_TOKEN is used for git push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update RSS feed if WAV exists
        run: |
          python <<'PYCODE'
          import datetime
          import xml.etree.ElementTree as ET
          import requests
          import sys

          # --- Configuration ---
          rss_path = "podcast/rss.xml"
          bucket_url_prefix = "https://storage.googleapis.com/nba_daily_summary_podcast_audios/"
          today = datetime.date.today().strftime("%Y-%m-%d")
          audio_filename = f"nba_daily_summary_podcast_{today}.wav"
          audio_url = f"{bucket_url_prefix}{audio_filename}"

          # Spotify owner info
          itunes_owner_name = "Damian Martínez Carmona"
          itunes_owner_email = "damian.martinez.carmona@gmail.com"  # <-- replace with your email

          # --- Check if today's file exists in GCS ---
          print(f"Checking if {audio_url} exists...")
          response = requests.head(audio_url)
          if response.status_code != 200:
              print(f"❌ File not found (HTTP {response.status_code}), skipping.")
              sys.exit(0)
          print("✅ File exists, proceeding to update RSS.")

          # --- Register namespaces ---
          ET.register_namespace('atom', "http://www.w3.org/2005/Atom")
          ET.register_namespace('itunes', "http://www.itunes.com/dtds/podcast-1.0.dtd")

          # --- Parse RSS ---
          tree = ET.parse(rss_path)
          channel = tree.find("channel")

          # --- Ensure itunes:owner exists ---
          if channel.find("{http://www.itunes.com/dtds/podcast-1.0.dtd}owner") is None:
              itunes_owner = ET.SubElement(channel, "{http://www.itunes.com/dtds/podcast-1.0.dtd}owner")
              ET.SubElement(itunes_owner, "{http://www.itunes.com/dtds/podcast-1.0.dtd}name").text = itunes_owner_name
              ET.SubElement(itunes_owner, "{http://www.itunes.com/dtds/podcast-1.0.dtd}email").text = itunes_owner_email

          # --- Ensure itunes:category exists ---
          if channel.find("{http://www.itunes.com/dtds/podcast-1.0.dtd}category") is None:
              itunes_category = ET.SubElement(channel, "{http://www.itunes.com/dtds/podcast-1.0.dtd}category", text="Sports")
              ET.SubElement(itunes_category, "{http://www.itunes.com/dtds/podcast-1.0.dtd}category", text="Basketball")

          # --- Avoid duplicates ---
          existing_titles = [item.findtext("title") for item in channel.findall("item")]
          if any(today in (t or "") for t in existing_titles):
              print(f"ℹ️ Episode for {today} already exists, skipping.")
              sys.exit(0)

          # --- Build new item ---
          pub_date = datetime.datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")
          item = ET.Element("item")
          ET.SubElement(item, "title").text = f"NBA Daily Summary — {today}"
          ET.SubElement(item, "description").text = f"Automated summary for {today}."
          ET.SubElement(item, "pubDate").text = pub_date
          ET.SubElement(item, "guid").text = audio_url
          ET.SubElement(item, "enclosure", url=audio_url, length="0", type="audio/wav")

          # --- Insert new item at the top (after channel metadata, before existing items) ---
          metadata_tags = [
              'title', 'link', 'language', 'description',
              '{http://www.w3.org/2005/Atom}link',
              '{http://www.itunes.com/dtds/podcast-1.0.dtd}owner',
              '{http://www.itunes.com/dtds/podcast-1.0.dtd}category'
          ]
          insert_index = max([i for i, child in enumerate(channel) if child.tag in metadata_tags]) + 1
          channel.insert(insert_index, item)

          # --- Write updated RSS ---
          tree.write(rss_path, encoding="UTF-8", xml_declaration=True)
          print(f"✅ Added episode for {today}: {audio_url}")
          PYCODE

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add podcast/rss.xml
          git commit -m "Add new episode $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push